//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yazokulum.com.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class zonguldak
    {
        public string Akademik_Birim { get; set; }
        public string Dersin_Kodu { get; set; }
        public string Dersin_Adı { get; set; }
        public Nullable<double> Teori { get; set; }
        public Nullable<double> Uygulama { get; set; }
        public Nullable<double> Kredi { get; set; }
        public Nullable<double> AKTS { get; set; }
        public string Bölümü { get; set; }
        public string Öğretim_Elemanı { get; set; }
        public string F10 { get; set; }
        public string F11 { get; set; }
        public string F12 { get; set; }
        public string F13 { get; set; }
        public string F14 { get; set; }
        public string F15 { get; set; }
        public string F16 { get; set; }
        public string F17 { get; set; }
        public string F18 { get; set; }
        public int id { get; set; }
    }
}
